# See https://cloudplatform.googleblog.com/2018/05/Kubernetes-best-practices-mapping-external-services.html
kind: Service
apiVersion: v1
metadata:
 name: mysqldb
spec:
 type: ClusterIP
 ports:
 - port: 3306
   targetPort: 30070
---
kind: Endpoints
apiVersion: v1
metadata:
 name: mysqldb
subsets:
 - addresses:
     - ip: 192.168.99.100 # IP of your MySQL instance
   ports:
     - port: 30070
