apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openmrs-modules-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

