kind: PersistentVolume
apiVersion: v1
metadata:
  name: openmrs-modules-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/modules"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openmrs-modules-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

