kind: PersistentVolume
apiVersion: v1
metadata:
  name: openmrs-modules-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/modules"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: openmrs-owa-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/owa"